name: flutter_app
description: A new Flutter application.
publish_to: none
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#version: 7.10.4+159
version: 8.01.04+1809

environment:
  #sdk: ">=2.12.0 <3.0.0"
  sdk: ">=3.5.4 <4.0.0"

module:
  androidX: true 
dependencies:
  flutter:
    sdk: flutter
#  url_launcher: ^6.3.1
#  dio: ^5.8.0+1
#  path_provider: ^2.1.5
#  permission_handler: ^11.3.1

  http: ^1.2.1
  flutter_spinkit: ^5.1.0
  connectivity_plus: ^6.1.1
  sqflite: ^2.0.2
  dio:
  path_provider:  ^2.0.9
  #carousel_slider:
  flutter_charts: ^0.5.2
  #charts_flutter:
  url_launcher: ^6.0.20
  #package_info_plus: ^5.0.1
  package_info_plus: ^8.0.3
  #launch_review: ^3.0.1
  flutter_date_pickers:
  #flutter_date_picker: ^0.1.2
  progress_dialog_null_safe: ^1.0.4
  #progress_dialog: ^1.2.0
  lottie:
  #lottie_flutter: ^0.2.0
  super_tooltip: ^1.0.1
  #permission_handler: ^9.2.0
  permission_handler: ^11.3.0
  another_flushbar: ^1.12.30
  geolocator: ^9.0.1
  geocoding: ^2.1.0
  clipboard:
  #device_info_plus: ^9.1.2
  device_info_plus: ^10.1.0
  webview_flutter: ^4.0.0

  #Because every version of flutter_test from sdk depends on path 1.7.0 and flutter_app depends on path 1.6.4, flutter_test from sdk is forbidden.
  path: ^1.8.0
  open_filex: ^4.5.0
  provider: ^6.0.0
#  simnumber:
  flutter_datetime_picker: ^1.5.1
  crypto: ^3.0.1
  flutter_cache_manager: ^3.3.0
  #rive: ^0.13.18

  #UDM----------
  shared_preferences: ^2.0.6
  flutter_form_builder: ^9.2.1
  fluttericon: ^2.0.0
  jiffy: ^6.0.0
  marquee: ^2.3.0
  blinking_text: ^1.0.2
  zoom_tap_animation: ^1.1.0
  syncfusion_flutter_pdfviewer: ^27.2.2
  shimmer: ^2.0.0
  animated_text_kit: ^4.2.2
  speech_to_text: ^7.0.0
  avatar_glow: ^2.0.2
  flutter_keyboard_visibility: ^6.0.0
  readmore: ^2.1.0
  #dropdown_search: ^4.0.1
  dropdown_search: ^6.0.1
  html: ^0.15.1
  #ssl_pinning_plugin: ^2.0.0
  feature_discovery:
    git:
      url: https://github.com/maheshj01/feature_discovery.git
      ref: master
  awesome_dialog: ^3.2.1
  font_awesome_flutter: ^9.1.0
  #share_plus: ^7.2.2
  share_plus: ^10.0.3
  flutter_staggered_animations: ^1.0.0
  animated_bottom_navigation_bar: ^0.3.0
  flutter_svg:
  #package_info: ^2.0.2
  expandable_text: ^2.3.0
  empty_widget: ^0.0.5
  whatsapp_unilink: ^2.0.0
  flutter_contacts: ^1.1.9+2
  #flutter_app_version_checker: ^0.3.2
  fluttertoast:

  #-----cris mmis
  get:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  #http_certificate_pinning:
  form_validator:
  syncfusion_flutter_charts:
  intl:
  intl_phone_field: ^3.2.0
  flutter_otp_text_field:
  pinput:



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
 
dependency_overrides:
  web: ^0.5.0
dev_dependencies:
  test:
  flutter_test:
    sdk: flutter

  build_runner:
  hive_generator: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/json/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BoldCondensed.ttf
        - asset: assets/fonts/Roboto-BoldCondensedItalic.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto-Condensed.ttf
        - asset: assets/fonts/Roboto-CondensedItalic.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
